project:
  type: website

website:
  title: "Notes"
  page-navigation: true
  reader-mode: false
  sidebar:
    logo: assets/logo.svg
    style: "docked"
    contents: auto
    border: true
    width: 120px
    collapse-level: 1
    alignment: "left"

format:
  html:
    theme: cosmo
    fontsize: 20px
    toc: true
    grid:
      sidebar-width: 200px
