project:
  type: website

website:
  title: "aGoodShoemaker"
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.md
      - text: "Notes"
        file: notes.md
      - text: "Music"
        file: music.md

format:
  html:
    theme: cosmo
    fontsize: 20px
    toc: true
